export const SET_LEVEL = 'SET_LEVEL';
export const RESET_LEVEL = 'RESET_LEVEL';
export const USER_ANSWER = 'USER_ANSWER';
export const INCORRECT_ANSWER = 'INCORRECT_ANSWER';
export const CORRECT_ANSWER = 'CORRECT_ANSWER';
